# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=200)),
                ('play_url', models.URLField(blank=True)),
                ('websocket_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('default', 'default'), ('applay', 'applay'), ('black', 'black'), ('ok', 'ok')], default=b'default', max_length=10)),
                ('switch', models.CharField(choices=[('open', 'open'), ('close', 'close')], default=b'close', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
