# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('default', 'default'), ('apply', 'apply'), ('black', 'black'), ('ok', 'ok')], default=b'default', max_length=10),
        ),
    ]
